server:
  port: 7006

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gym-wechat?characterEncoding=utf8&useSSL=false
    username: gym
    password: gym



